--Oracle CREATE INDEX examples

CREATE TABLE members(
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

select count(member_id) from members;

--if we want to search a member id 999 then
select * from members where member_id = 999;

--if we want to search record whose last name is Surtees then
select * from members where last_name = 'Surtees';

--But u can see , it is taking time to search , so to avoid this 
-- time, we are using indexes

create index i_members_lastname 
on members (last_name);

explain plan for
select * from members 
where last_name = 'Harse';

SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
    
    
EXPLAIN PLAN FOR
SELECT * FROM members
WHERE first_name = 'Delores';

SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());